---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.20.4

inputs:
  - name: dp-interactives-api

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-interactives-api/ci/scripts/build.sh
